name: Auto-Generate Changeset

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-changeset:
    name: Generate changeset from commits
    runs-on: ubuntu-latest

    # Skip if PR title contains [skip changeset]
    if: "!contains(github.event.pull_request.title, '[skip changeset]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0

      - name: Check for existing changesets
        id: check-changesets
        run: |
          if [ -d ".changeset" ] && [ "$(find .changeset -name '*.md' ! -name 'README.md' | wc -l)" -gt 0 ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "✓ Changesets already exist"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "No changesets found"
          fi

      - name: Generate changeset
        if: steps.check-changesets.outputs.exists == 'false'
        run: node scripts/auto-changeset.mjs

      - name: Commit and push changeset
        if: steps.check-changesets.outputs.exists == 'false'
        run: |
          if git diff --cached --quiet; then
            echo "No changeset was generated (no source changes or only docs/test/chore commits)"
            exit 0
          fi

          git commit -m "chore: add auto-generated changeset"
          git push

          echo "✓ Pushed auto-generated changeset to PR"

      - name: Comment on PR
        if: steps.check-changesets.outputs.exists == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.pulls.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const hasChangesetCommit = commits.some(c =>
              c.commit.message.includes('chore: add auto-generated changeset')
            );

            if (hasChangesetCommit) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '✅ **Changeset auto-generated** from your conventional commits!\n\nThe changeset has been added to this PR. Review it in the `.changeset/` directory.'
              });
            }
