name: changeset check
on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  pull-requests: read

jobs:
  changeset:
    name: Check changesets
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Check for changesets
      uses: changesets/action@v1
      with:
        version: pnpm version-packages
      continue-on-error: true
